name: CI

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
     
    services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_DATABASE: test_database
            MYSQL_ROOT_PASSWORD: password
          ports:
            - 3306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: test_database
        DB_USERNAME: root
        DB_PASSWORD: password

    steps:
    
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
    
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        
      - name: Install Dependencies
        run: composer install -n --prefer-dist
        
      - name: Generate key
        run: php artisan key:generate
        
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        
      - name: Installing Package.json
        run: npm install
        
      - name: Build Assets
        run: npm run build
          
      - name: Execute tests (Unit and Feature tests) via PEST
        run: vendor/bin/pest --parallel
        
      - name: Execute Larastan
        run: vendor/bin/phpstan analyze
        
      - name: Execute Laravel Pint
        run: vendor/bin/pint --test
